### ISSUE TITLE
Update Place schema to fit frontend

### ISSUE THREAD

**Issue by zhekaiii** [goodmeh/goodmeh-backend#23]
![Image](https://github.com/user-attachments/assets/1a632bf0-7d0f-4f60-b429-f97966cdf225)

To standardize between backend and frontend: use `updated_at` instead of `last_updated`. For now you can just put dummy data (or like empty string) in these fields. To put actual data in #24

**Comment by YaleChen299** [comment]
TODO:
1. place schema, with migration. + place query + test
2. place upsert (add some kind of hook such that _every place/review insert/update_ recompute the `review count` and `place weighted score`.

3. place route + test
